[package]
name = "rust-hdl-vcd-plot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "^0.3"
rand = "0.8.5"
itertools = "0.10.3"