[workspace]

members = [
    "rust-hdl-core",
    "rust-hdl-macros",
    "rust-hdl-test",
    "rust-hdl-widgets",
    "rust-hdl-synth",
    "rust-hdl-alchitry-cu",
    "rust-hdl-pcb",
    "rust-hdl-ok-frontpanel-sys",
#    "rust-hdl-schem-layout",
    "rust-hdl-ok",
]
