[package]
name = "rust-hdl-pcb-svg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.10.0"
rust-hdl-pcb-core = {path="../rust-hdl-pcb-core"}